os:
  - linux
  - osx

language: cpp

dist: xenial

git:
  depth: 1

install:
  - cmake --version
  - mkdir -p build
  - set +e; cd build; set -e; pwd
  - cmake .. -G "Unix Makefiles" -Wdev -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=ON
  - cat CMakeFiles/CMakeError.log || true
  - cat CMakeFiles/CMakeOutput.log || true
  - make -j2 VERBOSE=1
script:
  - ctest -j2 -VV
