language: cpp
sudo: true
script: cmake

git:
  depth: 1

matrix:
  include:
    - env:
      os: linux
    - env:
      os: osx

install:
  - mkdir -p build
  - set +e; cd build; set -e; pwd
  - cmake .. -G "Unix Makefiles" -Wdev -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TEST=ON
  - cat CMakeFiles/CMakeError.log || true
  - cat CMakeFiles/CMakeOutput.log || true
  - make -j2 VERBOSE=1
script:
  - ctest -j2 -VV