#shallow_clone: true
clone_depth: 1

image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

cache:
  - C:\ninja-build

install:
  - ps: |
      if (![IO.File]::Exists("C:\ninja-build\ninja.exe")) {
        Start-FileDownload 'https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip'
        7z x -y ninja-win.zip -oC:\ninja-build
      }
      $env:PATH="C:\ninja-build;$env:PATH"
  - for /f "tokens=1* delims=" %%i in ('"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath') do call "%%i\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM:x86=x86_amd64%
  - cmake --version
  - ninja --version
  - clang-cl --version
  - git submodule update --init --remote

build_script:
  - mkdir build && cd build
  - cmake .. -G Ninja -Wdev -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_TESTS=ON
  - ninja -v

test_script:
  - ctest -j2 --output-on-failure

deploy: off
